"""add error taxonomy tables

Revision ID: 03d875d9c97a
Revises: 5431a34d0363
Create Date: 2026-04-26 12:18:14.171313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d875d9c97a'
down_revision: Union[str, Sequence[str], None] = '5431a34d0363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('distinguishing_marker', sa.Text(), nullable=False),
    sa.Column('severity_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_error_categories_slug'))
    )
    op.create_table('error_subcategories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['error_categories.id'], name=op.f('fk_error_subcategories_category_id_error_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_subcategories')),
    sa.UniqueConstraint('slug', name=op.f('uq_error_subcategories_slug'))
    )
    op.create_index(op.f('ix_error_subcategories_category_id'), 'error_subcategories', ['category_id'], unique=False)
    op.create_table('error_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('canonical_example', sa.Text(), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('severity_hint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['error_subcategories.id'], name=op.f('fk_error_patterns_subcategory_id_error_subcategories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_patterns')),
    sa.UniqueConstraint('slug', name=op.f('uq_error_patterns_slug'))
    )
    op.create_index(op.f('ix_error_patterns_subcategory_id'), 'error_patterns', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_patterns_subcategory_id'), table_name='error_patterns')
    op.drop_table('error_patterns')
    op.drop_index(op.f('ix_error_subcategories_category_id'), table_name='error_subcategories')
    op.drop_table('error_subcategories')
    op.drop_table('error_categories')
    # ### end Alembic commands ###
