"""drop_student_dob

Revision ID: 19af2d227f34
Revises: 45ec09b0d696
Create Date: 2026-04-29 12:57:48.631195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19af2d227f34'
down_revision: Union[str, Sequence[str], None] = '45ec09b0d696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
