"""add stripe billing

Revision ID: 9060aa9c10aa
Revises: f7ad39986104
Create Date: 2026-04-24 11:58:22.481255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9060aa9c10aa'
down_revision: Union[str, Sequence[str], None] = 'f7ad39986104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('parent_monthly', 'teacher_monthly', name='plan'), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'incomplete', name='subscription_status'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_subscriptions_organization_id'))
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_trial_ends_at'), 'subscriptions', ['trial_ends_at'], unique=False)
    op.create_index('uq_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=True, postgresql_where=sa.text('stripe_subscription_id IS NOT NULL'))
    op.create_table('subscription_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_events_subscription_id_subscriptions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_events')),
    sa.UniqueConstraint('stripe_event_id', name=op.f('uq_subscription_events_stripe_event_id'))
    )
    op.create_index(op.f('ix_subscription_events_created_at'), 'subscription_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_event_type'), 'subscription_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_subscription_events_processed_at'), 'subscription_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.add_column('organizations', sa.Column('subscription_status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'incomplete', name='subscription_status', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'subscription_status')
    op.drop_index(op.f('ix_subscription_events_subscription_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_processed_at'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_type'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_created_at'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index('uq_subscriptions_stripe_subscription_id', table_name='subscriptions', postgresql_where=sa.text('stripe_subscription_id IS NOT NULL'))
    op.drop_index(op.f('ix_subscriptions_trial_ends_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    sa.Enum(name='subscription_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='plan').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
