"""add clerk_org_id to organizations

Revision ID: f7ad39986104
Revises: b9189088c385
Create Date: 2026-04-23 20:04:04.483259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ad39986104'
down_revision: Union[str, Sequence[str], None] = 'b9189088c385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('clerk_org_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', type_='unique')
    op.drop_column('organizations', 'clerk_org_id')
    # ### end Alembic commands ###
